### ISSUE TITLE
Simple usage example?

### ISSUE THREAD

**Issue by faceleg** [bennyhat/protractor-istanbul-plugin#1]

**Comment by bennyhat** [comment]
Hey Michael,
   I'll take some time later today to get the readme updated with actual usage details.
Ben

**Comment by faceleg** [comment]
That would be amazing!

![](http://25.media.tumblr.com/tumblr_md3nrgoETF1rzqj3uo1_1280.jpg)

**Comment by bennyhat** [comment]
Hey - I just added in details to the [readme](https://github.com/bennyhat/protractor-istanbul-plugin/blob/master/README.md). Additionally, I will try to find time to publish a minor, minor, minor version update to get those details added to the npm package page as well.

**Comment by faceleg** [comment]
Yes this is much more helpful! I had no idea I had to instrument the code myself and was scratching my head over the lack of output.

Thank you very much for taking the time to do this
